# Generated by Django 3.2.3 on 2021-05-29 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='books', to='graphbooks.Genre')),
                ('primary_genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_genre_books', to='graphbooks.genre')),
                ('similar', models.ManyToManyField(blank=True, related_name='_graphbooks_book_similar_+', to='graphbooks.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
